# Generated by Django 5.2 on 2025-05-16 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DetectionResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("color_name", models.CharField(max_length=50)),
                ("image", models.ImageField(upload_to="detected_images/")),
                ("detected_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
